In [2]:
#import modules
import matplotlib.pyplot as plt
import numpy as np

## Vectors

### Scalar Multiplication

In [2]:
vec = [3,4,5,2]
s = 3

vec*s

[3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2]

In [3]:
vec =np.array([3,4,5,2])
s = 3

vec*s

array([ 9, 12, 15,  6])

### Dot Product

In [3]:
v1 = np.array([4,5,6,2])
v2 = np.array([-4,3,0,5])

np.dot(v1,v2)

9

#### Orthogonality

if the dot products of vectors are equal to 0, then we can call them orthogonal to each other.

In [4]:
v4 = np.array([-4,3,1])
v5 = np.array([2,3,-1])

np.dot(v4,v5)

# vector v4 orthogonal to vector v5.

0

## Matrices

In [5]:
np.eye(3)
#it gives 3*3 identity matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.zeros((3,4))
#it gives 3*4 zero matrices

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.full((5,2),7)

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

### Transpose

In [9]:
M = np.array ([[1,2,3],
              [4,5,6],
              [7,8,9]])
transposed_M = np.transpose(M)
print(M)
print(transposed_M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Matrix Multiplication

In [10]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]]) # 2x3

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]]) # 3x2

result_matrixMult = matrix1 @ matrix2
print(result_matrixMult)

[[ 58  64]
 [139 154]]


### Matrix Inverse

In [11]:
matrix = np.array([[4, 7],
                   [2, 6]])

inverse_matrix = np.linalg.inv(matrix)

print(matrix)
print(inverse_matrix)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


### Eigenvalues and Eigenvectors

In [13]:
matrix = np.array([[4, -2],
                   [1,  1]])

# Compute Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)


print("Matrice:")
print(matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrice:
[[ 4 -2]
 [ 1  1]]

Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
